version: '3.8'

services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"

    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '512MB'
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node_app
    ports:
      - "9999:9999" 

networks:
  default:
    driver: bridge
    name: load-socket-chat
